### ISSUE TITLE
V9 Option

### ISSUE THREAD

**Issue by OpencloudPro** [CodazziS/odoo_addons#14]
Hi, are you thinking about creating a gantt view app for odoo v9 community version? I think it would have very much demand! Thanks

**Comment by yanndc** [comment]
Indeed. Too late for me as I finally trashed Odoo, but for sure it would be
welcome for a lot of people.

2016-06-06 18:18 GMT-04:00 Opencloud notifications@github.com:

**Comment by KaloyanNaumov** [comment]
+1. It would be great to have Gantt Charts in the v9 Community edition!

**Comment by CodazziS** [comment]
Hello,
I know you want a gantt for Odoo 9, but I don't work anymore on Odoo. I just maintain my addon for bugs. 
My addon work with the original gantt (odoo addon) and rewrite the view. In Odoo 9, no gantt exist, so, I can't port this addon to odoo9. I don't have enough time for develop a full gantt addon.

Sorry to can't help you. I hope you found a community who will do it.

**Comment by levkar** [comment]
@stephane- 
I already upgraded to v4.0 and made few various fixes. should i keep sending pull requests to your repo or maintain it seperately?

**Comment by CodazziS** [comment]
Hello,
Do you mean dxhtml V4 ? If yes, I must look If the version is compatible. I think, the last year dhtmlx are change the licence of the library. I check that this week and If it's compatible, we Can upgrade that.

**Comment by levkar** [comment]
There has been lots of discussion about the use of dhtmx gantt licensing with various odoo versions. 

https://github.com/odoo/odoo/issues/9640

Is the license of current dhtmlx gantt version that is used compatible with AGPLv3?

**Comment by CodazziS** [comment]
CF #21
