### ISSUE TITLE
Event doesn t appear if it starts next year

### ISSUE THREAD

**Issue by Jeffys** [CodazziS/odoo_addons#15]
Hi Stephane,
First of all thanks for this module, gantt improvement, wich is much better than the original one.
But I have an issue:
If I have on event starting next year (2017) it doesn't appear on the gantt chart, do you have an idea?
I didn t manage to find the pb...
Thans again.
Jeffys

**Comment by CodazziS** [comment]
Hello,
Sorry for the responce time.
Can you test the fix (in the version 1.4) and confirm it's working ?

Regards,
Stéphane

**Comment by Jeffys** [comment]
Hi Stephane,

thanks a lot for this it works now.
I also modify your code in order to be able to use the filters.
Here are the modifications
Thanks again.
Are you french?

Cheers,
Jeff

2016-06-28 5:39 GMT+08:00 Stéphane Codazzi notifications@github.com:

**Comment by CodazziS** [comment]
Hi, 
Thank you for testing.
Yes, I'm french

Regards, 
Stéphane
