### ISSUE TITLE
Width for day/week/month view compared to year

### ISSUE THREAD

**Issue by DustinBrett** [CodazziS/odoo_addons#25]
The year view is able to size itself to fit into the window without scrollbars but the day/week/month views don't. Is it possible to fix this or change this? If so could someone help point me in the right direction. I was reading through dhtmlxgantt.js but it's nearly 10,000 lines and references many width elements.

Thanks.

**Comment by CodazziS** [comment]
Do you mean vertical scrollbar or horizontal scrollbar ?

If it's the horizontal scrollbar, should be fix by #24 (currently only on the dev branch)

**Comment by DustinBrett** [comment]
I mean horizontal I guess. Like how Year view fits on the screen and the other views do not. I will look into that fix if you think it will fix this issue.

**Comment by DustinBrett** [comment]
I tried adding:

gantt.config.autosize = "y";

I also tried:

gantt.config.autosize = "x";

Neither seemed to have much effect on my issue. Here are 2 screenshots showing the long scrollbar with Day view and no scrollbar with Year view. I want to find a way to make Day view compact like Year view. I am willing to eliminate some column info if needed, I just need help on where to make these changes.

![hscroll](https://cloud.githubusercontent.com/assets/16656318/17902939/4314afc0-691e-11e6-96c8-495a412b0b96.png)
![noscroll](https://cloud.githubusercontent.com/assets/16656318/17902940/431604e2-691e-11e6-8db1-c6ccccb39952.png)

**Comment by CodazziS** [comment]
Ho, I see.
Sorry for my last comment, I mean say "vertical scrollbar", not horizontal.

For the day view, web can't hide columns, but, levkar has remake scales of day/week/months/year. 
Maybe changes can help you ?
Commit here :  https://github.com/stephane-/odoo_addons/commit/45d36e071fa162d2d17ae11afab6623bf3a5abf4

**Comment by DustinBrett** [comment]
No prob, I figured you meant vertical. That change from levkar looks promising, I will try that. Thanks again.

**Comment by DustinBrett** [comment]
That fix was what I needed to point me in the right direction. Once we removed the subscales it sized a lot better.
