### ISSUE TITLE
Column res_users.gantt_improvement_zoom missing

### ISSUE THREAD

**Issue by beauprgu** [CodazziS/odoo_addons#28]
I am getting the following error message in the odoo log file:

openerp.sql_db: Programming error: column res_users.gantt_improvement_zoom does not exist

Note: Odoo 8 - Addon version 8.0.2.0

**Comment by beauprgu** [comment]
It seems that the problem be in file "gantt_improvement.py"

If you remove the following:

 _columns = {
        'gantt_improvement_zoom': fields.selection(
            [
            ('1','Day'),
            ('2','Week'),
            ('3','Year'),
            ('4','Week'),
            ],
            'Default zoom',
            help="Choose the default zoom for the gantt view"),

It does go back to normal or something that look like normal. But, I suppose Stéphane has put it there for a reason!

**Comment by CodazziS** [comment]
So sorry for the bug, it's du to future feature ( #23 ).

It's fixed in 8.0 branch

**Comment by beauprgu** [comment]
Thanks
