### ISSUE TITLE
Problems calculating time and duration of manufacturing orders

### ISSUE THREAD

**Issue by oggito** [CodazziS/odoo_addons#3]
Hi,

I have installed the new version of the gantt improvement. I found 2 issues:
1. The web gantt is influencing the gantt improvement module, when we install the wen gantt app, the gantt improvement gantt is not working anymore.
1. When we use the gantt improvement app, the gantt chart does not take into account the duration of the orders. For example, we have a manufacturing order of 500 hours, the gantt displays that the order will last till 2017? It was supposed to last till the 19.10.2015.

Could you please check the issue and let us know, how to solve this problem?

Thank again!

**Comment by CodazziS** [comment]
Hi,

1- The "gantt improvement" module have dependence with the "web gantt" module. If you uninstall the web gantt, gantt improvement will be uninstalled too. 

2- I will search the problem in the next days

**Comment by oggito** [comment]
Hi,

thank you for your reply. Actually it is the other way about at our instance. When we have the gannt web installed, the gantt improvement is not showing at all. Nothing. When we uninstall the gantt web, the gantt improvement shows, but it is not working properly.

I would like to make you a proposal.
- I could give you even access to our instance, it is on a cloud server.
- Please let us know, how we can finance your effort in making the module working for us

Thank you.

Best Regards,
Ognyan

**Comment by CodazziS** [comment]
Hello,
For the moment I don't have lot of time, but I can see this end of week.
If your instance has no personal data or confidential data, you can give me an access (by mail if you want: stephane.codazzi@gmail.com) otherwise, you can just tell me in what module you can see the gantt (project, ...?) 

Thank you for your interest and your help to improve my addon.

Best Regards,
Stéphane

**Comment by oggito** [comment]
Hello,

Both apps - the gantt web and the gantt improvement are working together. But there is a problem with the gantt displaying the right number of hours.
Here is the current problem, if we solve this, that would be great and huge progress.

A have a working center (Machine), which works for example from 09:00 till 22:00 every day.

I start a manufacturing order, which calculates that the needed time for completion is 28 hours. That means if it starts on 21st Sep at 09:00, it should end on the 23rd Sep. at 13:00. This is the calculate time in the working order.

At the same time the gantt displays that till the 19th of OCTOBER! This is really very wrong. It means, that the gantt does not take into account the working hours of the resource.

I am attaching a screenshot.

Your support would be highly appreciated.

Thanks

**Comment by CodazziS** [comment]
Hello, 
I understand your problem.
I will look and try to fix it. I come back to you when I fixed it.

**Comment by oggito** [comment]
Hi,
I hope that you will fix that. This was not working even in the standard version in odoo and with lots of limitations in the old versions of erp.
An ERP without a proper functioning Gantt chart cannot be really used in a manufacturing company.

Thank you.

Best Regards,
Ognyan

**Comment by CodazziS** [comment]
Hi,
I know that's a really problem, and I want to fix it,  but I need to know the module who display the gantt. 

I suppose it's the "MRP" module ?

**Comment by oggito** [comment]
Hello,

yes, this is the MRP module, manufacturing. Then work orders by resources.

Hope this helps you further.

Thanks.

**Comment by CodazziS** [comment]
Hello, 
I think it's now fixed.
Can you upgrade gantt improvement to V 1.2 and test if the date end is now correct ?

Best Regards,
Stéphane

**Comment by oggito** [comment]
Can I download it and reinstall it from the GetHub?

**Comment by CodazziS** [comment]
I don't know what is GetHub (Github ?) but you can install it from Github, or from odoo store, in settings, and app tab directly in Odoo

**Comment by oggito** [comment]
I meant github, technical error in typing. Sorry. I downloaded the module form the odoo store and saved it. Afterwards I imported the version, which is supposed to be 1.2. The zip file is called "gantt_improvement-8.0.1.2.zip”.

When I activate the module it says it is version 8.0.1.1

Then an update occurs in my odoo instance. But I try to update it and login, nothing happens. It says “Install App”, I type in my credentials and nothing happens. Never ever had these issues before. I am using Odoo on Ubuntu and I have been working with it in our company since version 6.1., so for years.

Do you have any ideas how to upgrade?

Could you send me the updated new version as a zip.

Thanks.

**Comment by oggito** [comment]
Hello,

I do confirm, that the bugfix is working just great. 
The gantt chart takes into account the working hours of the working centers and displays the chart correctly. The start and end dates are now exactly the right ones.

For first time since years we have a working gantt chart for odoo.

This is a significant feature for every manufacturing company. I cannot imagine myself using odoo any longer without this module.

Thank you.

I would like to make a small contribution to this module. Please let me know how.

Ognyan

P. S. If you want to make the gantt even better, think about implementing a feature like this one:
- let us have a specific working center.
- we have same working orders on it. BUT these orders have been placed in a way, that they are not following each other. So you simply lose capacity in that way. 
- A user would be interested to know and see that in advance. So if we choose to view the working orders by working centers, we should be able to see that there ist still for example free capacity between let us say 2 working orders, so the chart bar for the working center should be in a different color.
- If for some reason working orders are overlapping, the chart bar in that area could be red, telling us  that we need to reorganize the planing.

Hope this makes sense.

**Comment by CodazziS** [comment]
Hello,
The gantt_improvement can display arrow between two tasks, but informations need to be given by the parent module (here MRP module).
I had use this feature in Odoo 7, in "long term project" (Removed in Odoo8...).

It's good idea to implement that in Odoo8, but the MRP module give not enought informations to the gantt for do that. Maybe I can create a specific parser for the MRP, for found by myself the informations. I will investigate the way when I will have more time.

I don't do this module for money or other contributions, but if you really want, maybe you can visit this site : https://www.paypal.me/codazzi
