### ISSUE TITLE
 Move gantt_improvement to OCa

### ISSUE THREAD

**Issue by rafaelbn** [CodazziS/odoo_addons#6]
Hi @stephane- ,

What do you think about contributing in OCA moving this module https://github.com/stephane-/gantt_improvement?

It looks interesting

Regards

**Comment by CodazziS** [comment]
Hello,
I don't know the pre-required for moving this module in OCA.
Can you tell me more ?

Stephane

**Comment by rafaelbn** [comment]
You can check https://odoo-community.org/page/code
