### ISSUE TITLE
A bug in Odoo8.0 Gantt chart - Have to click two times on Gantt icon to load right data

### ISSUE THREAD

**Issue by sergueikp** [CodazziS/odoo_addons#8]
OS concerned : Windows 7 (also may be Ubuntu but not tested)
Odoo version:  Odoo 8.0-20151209
Gantt_improvement version : 1.2

How to reproduce the bug:
Go to Project> Projects > click on Gantt view in right up corner
Go to Tasks >  click one time on Gantt view in right up corner

Actual behaviour:
You will see the gantt chart of Projects
Expected behaviour:
You should see Tasks gantt chart

Note:
If you click two times on the gantt view icon it will load right gantt chart. 

Best reagrds.

**Comment by mlaitinen** [comment]
Can confirm this on Debian Jessie.

**Comment by DustinBrett** [comment]
Has anyone made any headway with this issue?

**Comment by DustinBrett** [comment]
FYI, I added:

gantt.clearAll();

After gantt.init inside the function draw_gantt to fix this issue for myself.
